# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_STARFIVE) += jh7100-beaglev-starlight-a1.dtb jh7100-beaglev-starlight.dtb jh7100-starfive-visionfive-v1.dtb
dtb-$(CONFIG_SOC_STARFIVE_DUBHE) += dubhe80_fpga.dtb dubhe90_fpga.dtb dubhe90_fpga_dual.dtb
