# SPDX-License-Identifier: GPL-2.0
#
# Makefile for RTC class/drivers.
#

obj-$(CONFIG_VIDEO_STARFIVE_VIN_SENSOR_OV5640) += ov5640_dvp.o
obj-$(CONFIG_VIDEO_STARFIVE_VIN_SENSOR_SC2235) += sc2235.o
obj-$(CONFIG_VIDEO_STARFIVE_VIN_SENSOR_IMX219) += imx219_mipi.o
obj-$(CONFIG_VIDEO_STARFIVE_VIN) += video_stf_vin.o
video_stf_vin-objs += stf_vin.o stf_event.o stf_isp.o stf_csi.o
