# SPDX-License-Identifier: GPL-2.0
#
# Makefile for StarFive camera subsystem driver.
#

starfive-camss-objs += \
		stf_camss.o \
		stf_video.o

obj-$(CONFIG_VIDEO_STARFIVE_CAMSS) += starfive-camss.o \
