# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2021 StarFive Technology Co., Ltd.
#
# Makefile for starfive v4l2 driver framework
#
obj-$(CONFIG_VIN_SENSOR_OV5640) += ov5640.o
obj-$(CONFIG_VIN_SENSOR_SC2235) += sc2235.o
obj-$(CONFIG_VIN_SENSOR_OV4689) += ov4689_mipi.o
obj-$(CONFIG_VIN_SENSOR_IMX219) += imx219_mipi.o
obj-$(CONFIG_VIDEO_STARFIVE_VIN) += stfcamss.o \
								stf_event.o \
								stf_dvp.o \
								stf_csi.o \
								stf_csiphy.o \
								stf_isp.o \
								stf_video.o \
								stf_vin.o \
								stf_vin_hw_ops.o \
								stf_csi_hw_ops.o \
								stf_csiphy_hw_ops.o \
								stf_isp_hw_ops.o \
								stf_dvp_hw_ops.o
