# StarFive Platform Support
obj-$(CONFIG_SND_SOC_JH7110_PDM) += jh7110_pdm.o

obj-$(CONFIG_SND_SOC_JH7110_PWMDAC) += jh7110_pwmdac.o

obj-$(CONFIG_SND_SOC_JH7110_SPDIF) += spdif.o
spdif-y := jh7110_spdif.o
spdif-$(CONFIG_SND_SOC_JH7110_SPDIF_PCM) += jh7110_spdif_pcm.o

obj-$(CONFIG_SND_SOC_JH7110_TDM) += jh7110_tdm.o
