# SPDX-License-Identifier: GPL-2.0
#
# Makefile for RTC class/drivers.
#

obj-$(CONFIG_FB_STARFIVE)		+= starfive_fb.o starfive_lcdc.o starfive_vpp.o \
					starfive_display_dev.o starfive_displayer.o

obj-$(CONFIG_FB_STARFIVE_HDMI_ADV7513)		+= adv7513.o
