# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2021 StarFive Technology Co., Ltd.
#
starfive-drm-y := starfive_drm_drv.o \
		  starfive_drm_gem.o \
		  starfive_drm_crtc.o \
		  starfive_drm_encoder.o \
		  starfive_drm_plane.o \
		  starfive_drm_lcdc.o \
		  starfive_drm_vpp.o

obj-$(CONFIG_DRM_STARFIVE) += starfive-drm.o
