# SPDX-License-Identifier: GPL-2.0

starfive-drm-y := starfive_drm_drv.o \
		  starfive_drm_gem.o \
		  starfive_drm_crtc.o \
		  starfive_drm_encoder.o \
		  starfive_drm_plane.o \
		  starfive_drm_lcdc.o \
		  starfive_drm_vpp.o \
		  starfive_drm_dsi.o \
		  starfive_drm_seeedpanel.o


obj-$(CONFIG_DRM_STARFIVE) += starfive-drm.o
